### ISSUE TITLE
pip3 installation of zxing-cpp 2.2.0 fails in NVDIA Jetson

### ISSUE THREAD

**Issue by SIGLOST** [zxing-cpp/zxing-cpp#803]
Hi, 

Any idea what dependency I might be missing to be able to build and install `zxing-cpp version 2.2.0` on a NVIDIA Jetson using `pip3`?

```
root@jetson-nx:~# sudo apt-cache show nvidia-jetpack
Package: nvidia-jetpack
Version: 5.1.1-b56
Architecture: arm64
Maintainer: NVIDIA Corporation
```

```
root@jetson-nx:~# pip3 --version
pip 24.1.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
```

```
root@jetson-nx:~# cmake --version
cmake version 3.16.3
```

```
root@jetson-nx:~# pip3 install zxing-cpp==2.2.0
Collecting zxing-cpp==2.2.0
  Downloading zxing-cpp-2.2.0.tar.gz (652 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 652.8/652.8 kB 3.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: zxing-cpp
  Building wheel for zxing-cpp (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for zxing-cpp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [283 lines of output]
      running bdist_wheel
      running build
      running build_ext
      -- The C compiler identification is GNU 9.4.0
      -- The CXX compiler identification is GNU 9.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
      -- Check if compiler accepts -pthread
      -- Check if compiler accepts -pthread - yes
      -- Found Threads: TRUE
      -- Performing Test COMPILER_NEEDS_FLOAT_STORE
      -- Performing Test COMPILER_NEEDS_FLOAT_STORE - Success
      CMake Warning (dev) at /tmp/pip-build-env-36visyz0/overlay/share/cmake/pybind11/FindPythonLibsNew.cmake:101 (message):
        Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
        are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
        the cmake_policy command to set the policy and suppress this warning, or
        preferably upgrade to using FindPython, either by calling it explicitly
        before pybind11, or by setting PYBIND11_FINDPYTHON ON before pybind11.
      Call Stack (most recent call first):
        /tmp/pip-build-env-36visyz0/overlay/share/cmake/pybind11/pybind11Tools.cmake:50 (find_package)
        /tmp/pip-build-env-36visyz0/overlay/share/cmake/pybind11/pybind11Common.cmake:202 (include)
        /tmp/pip-build-env-36visyz0/overlay/share/cmake/pybind11/pybind11Config.cmake:250 (include)
        zxing.cmake:29 (find_package)
        CMakeLists.txt:27 (zxing_add_package)
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3.7")
      -- Found PythonLibs: /usr/lib/aarch64-linux-gnu/libpython3.8.so
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Found pybind11: /tmp/pip-build-env-36visyz0/overlay/include (found version "2.13.1")
      -- Configuring done (5.4s)
      -- Generating done (0.1s)
      CMake Warning:
        Manually-specified variables were not used by the project:
      
          VERSION_INFO
      
      
      -- Build files have been written to: /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/build/temp.linux-aarch64-cpython-38
      [  1%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/BarcodeFormat.cpp.o
      [  2%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/BitMatrix.cpp.o
      [  2%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/BitArray.cpp.o
      [  3%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/ConcentricFinder.cpp.o
      [  7%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/GenericGF.cpp.o
      [  7%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/ECI.cpp.o
      [  7%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/CharacterSet.cpp.o
      [  7%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/BitMatrixIO.cpp.o
      [  8%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/GenericGFPoly.cpp.o
      [  9%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/GTIN.cpp.o
      [ 10%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/TextUtfEncoding.cpp.o
      [ 11%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/Utf.cpp.o
      [ 12%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/ZXBigInteger.cpp.o
      [ 13%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/BinaryBitmap.cpp.o
      [ 14%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/BitSource.cpp.o
      [ 15%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/Content.cpp.o
      [ 16%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/GlobalHistogramBinarizer.cpp.o
      [ 16%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/GridSampler.cpp.o
      [ 17%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/HRI.cpp.o
      [ 18%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/HybridBinarizer.cpp.o
      [ 19%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/MultiFormatReader.cpp.o
      [ 20%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/PerspectiveTransform.cpp.o
      [ 21%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/ReadBarcode.cpp.o
      /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/HRI.cpp: In function ‘std::string ZXing::HRIFromISO15434(std::string_view)’:
      /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/HRI.cpp:311:9: warning: comparison is always true due to limited range of data type [-Wtype-limits]
        311 |   if (0 <= c && c <= 0x20)
            |       ~~^~~~
      [ 22%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/ReedSolomonDecoder.cpp.o
      [ 23%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/Result.cpp.o
      [ 24%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/ResultPoint.cpp.o
      [ 25%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/TextDecoder.cpp.o
      [ 26%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/WhiteRectDetector.cpp.o
      [ 27%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/ReedSolomonEncoder.cpp.o
      [ 28%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/TextEncoder.cpp.o
      [ 29%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/MultiFormatWriter.cpp.o
      [ 30%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/aztec/AZDecoder.cpp.o
      [ 31%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/aztec/AZDetector.cpp.o
      [ 32%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/aztec/AZReader.cpp.o
      [ 32%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/aztec/AZHighLevelEncoder.cpp.o
      [ 33%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/aztec/AZEncoder.cpp.o
      [ 34%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/aztec/AZToken.cpp.o
      [ 35%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/aztec/AZWriter.cpp.o
      [ 36%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/datamatrix/DMBitLayout.cpp.o
      [ 37%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/datamatrix/DMVersion.cpp.o
      [ 38%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/datamatrix/DMDataBlock.cpp.o
      [ 39%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/datamatrix/DMDecoder.cpp.o
      [ 40%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/datamatrix/DMDetector.cpp.o
      [ 41%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/datamatrix/DMReader.cpp.o
      [ 42%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/datamatrix/DMECEncoder.cpp.o
      [ 43%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/datamatrix/DMHighLevelEncoder.cpp.o
      [ 44%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/datamatrix/DMSymbolInfo.cpp.o
      [ 45%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/datamatrix/DMWriter.cpp.o
      [ 46%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/maxicode/MCBitMatrixParser.cpp.o
      [ 47%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/maxicode/MCDecoder.cpp.o
      [ 48%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/maxicode/MCReader.cpp.o
      [ 49%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODUPCEANCommon.cpp.o
      [ 50%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODCode128Patterns.cpp.o
      [ 50%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODCodabarReader.cpp.o
      [ 51%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODCode39Reader.cpp.o
      [ 52%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODCode93Reader.cpp.o
      [ 53%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODCode128Reader.cpp.o
      [ 54%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODDataBarCommon.cpp.o
      [ 55%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODDataBarReader.cpp.o
      [ 56%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODDataBarExpandedBitDecoder.cpp.o
      [ 57%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODDataBarExpandedReader.cpp.o
      [ 58%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODITFReader.cpp.o
      [ 59%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODMultiUPCEANReader.cpp.o
      [ 60%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODReader.cpp.o
      [ 61%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODRowReader.cpp.o
      [ 62%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODCodabarWriter.cpp.o
      [ 63%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODCode39Writer.cpp.o
      [ 64%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODCode93Writer.cpp.o
      [ 65%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODCode128Writer.cpp.o
      [ 66%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODEAN8Writer.cpp.o
      [ 66%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODEAN13Writer.cpp.o
      [ 67%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODITFWriter.cpp.o
      [ 68%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODUPCEWriter.cpp.o
      [ 69%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODUPCAWriter.cpp.o
      In file included from /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/oned/ODEAN8Writer.cpp:9:
      /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/oned/ODUPCEANCommon.h: In instantiation of ‘std::array<int, N> ZXing::OneD::UPCEANCommon::DigitString2IntArray(const std::__cxx11::basic_string<T>&, int) [with long unsigned int N = 8; T = wchar_t]’:
      /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/oned/ODEAN8Writer.cpp:26:62:   required from here
      /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/oned/ODUPCEANCommon.h:72:21: warning: comparison of integer expressions of different signedness: ‘const value_type’ {aka ‘const wchar_t’} and ‘int’ [-Wsign-compare]
         72 |  else if (in.back() != checkDigit)
      /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/oned/ODCode128Writer.cpp: In function ‘int ZXing::OneD::ChooseCode(const wstring&, int, int)’:
      /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/oned/ODCode128Writer.cpp:84:61: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const wchar_t’ [-Wsign-compare]
         84 |    if (c < ' ' || (oldCode == CODE_CODE_A && (c < '`' || (c >= ESCAPE_FNC_1 && c <= ESCAPE_FNC_4)))) {
            |                                                           ~~^~~~~~~~~~~~~~~
      /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/oned/ODCode128Writer.cpp:84:82: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const wchar_t’ [-Wsign-compare]
         84 |    if (c < ' ' || (oldCode == CODE_CODE_A && (c < '`' || (c >= ESCAPE_FNC_1 && c <= ESCAPE_FNC_4)))) {
            |                                                                                ~~^~~~~~~~~~~~~~~
      In file included from /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/oned/ODEAN13Writer.cpp:9:
      /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/oned/ODUPCEANCommon.h: In instantiation of ‘std::array<int, N> ZXing::OneD::UPCEANCommon::DigitString2IntArray(const std::__cxx11::basic_string<T>&, int) [with long unsigned int N = 13; T = wchar_t]’:
      /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/oned/ODEAN13Writer.cpp:31:63:   required from here
      /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/oned/ODUPCEANCommon.h:72:21: warning: comparison of integer expressions of different signedness: ‘const value_type’ {aka ‘const wchar_t’} and ‘int’ [-Wsign-compare]
         72 |  else if (in.back() != checkDigit)
      [ 70%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/oned/ODWriterHelper.cpp.o
      [ 71%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/pdf417/PDFBarcodeValue.cpp.o
      [ 72%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/pdf417/PDFBoundingBox.cpp.o
      [ 73%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/pdf417/PDFCodewordDecoder.cpp.o
      In file included from /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/oned/ODUPCEWriter.cpp:9:
      /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/oned/ODUPCEANCommon.h: In instantiation of ‘std::array<int, N> ZXing::OneD::UPCEANCommon::DigitString2IntArray(const std::__cxx11::basic_string<T>&, int) [with long unsigned int N = 8; T = wchar_t]’:
      /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/oned/ODUPCEWriter.cpp:26:101:   required from here
      /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/core/src/oned/ODUPCEANCommon.h:72:21: warning: comparison of integer expressions of different signedness: ‘const value_type’ {aka ‘const wchar_t’} and ‘int’ [-Wsign-compare]
         72 |  else if (in.back() != checkDigit)
      [ 74%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/pdf417/PDFDecoder.cpp.o
      [ 75%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/pdf417/PDFDetectionResult.cpp.o
      [ 76%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/pdf417/PDFDetectionResultColumn.cpp.o
      [ 77%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/pdf417/PDFDetector.cpp.o
      [ 78%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/pdf417/PDFModulusGF.cpp.o
      [ 79%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/pdf417/PDFModulusPoly.cpp.o
      [ 80%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/pdf417/PDFReader.cpp.o
      [ 81%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/pdf417/PDFScanningDecoder.cpp.o
      [ 82%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/pdf417/PDFEncoder.cpp.o
      [ 83%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/pdf417/PDFHighLevelEncoder.cpp.o
      [ 83%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/pdf417/PDFWriter.cpp.o
      [ 84%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/qrcode/QRCodecMode.cpp.o
      [ 85%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/qrcode/QRErrorCorrectionLevel.cpp.o
      [ 86%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/qrcode/QRVersion.cpp.o
      [ 87%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/qrcode/QRBitMatrixParser.cpp.o
      [ 88%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/qrcode/QRDataBlock.cpp.o
      [ 89%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/qrcode/QRDecoder.cpp.o
      [ 90%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/qrcode/QRDetector.cpp.o
      [ 91%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/qrcode/QRFormatInformation.cpp.o
      [ 92%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/qrcode/QRReader.cpp.o
      [ 93%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/qrcode/QREncoder.cpp.o
      [ 94%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/qrcode/QRMaskUtil.cpp.o
      [ 95%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/qrcode/QRMatrixUtil.cpp.o
      [ 96%] Building CXX object ZXing/CMakeFiles/ZXing.dir/src/qrcode/QRWriter.cpp.o
      [ 97%] Building C object ZXing/CMakeFiles/ZXing.dir/src/libzueci/zueci.c.o
      [ 98%] Linking CXX static library libZXing.a
      [ 98%] Built target ZXing
      [ 99%] Building CXX object CMakeFiles/zxingcpp.dir/zxing.cpp.o
      In file included from /tmp/pip-build-env-36visyz0/overlay/include/pybind11/pybind11.h:19,
                       from /tmp/pip-install-p_grebl8/zxing-cpp_22c0ab97b9434f13aa42df442179016b/zxing.cpp:19:
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:227:49: error: class template argument deduction failed:
        227 | struct handle_type_name<typing::Literal<Literals...>> {
            |                                                 ^~~
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:227:49: error: no matching function for call to ‘StringLiteral(StringLiteral<...auto...>)’
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:104:15: note: candidate: ‘template<long unsigned int N> StringLiteral(const char (&)[N])-> pybind11::typing::StringLiteral<N>’
        104 |     constexpr StringLiteral(const char (&str)[N]) { std::copy_n(str, N, name); }
            |               ^~~~~~~~~~~~~
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:104:15: note:   template argument deduction/substitution failed:
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:227:49: note:   mismatched types ‘const char [N]’ and ‘StringLiteral<...auto...>’
        227 | struct handle_type_name<typing::Literal<Literals...>> {
            |                                                 ^~~
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:103:8: note: candidate: ‘template<long unsigned int N> StringLiteral(pybind11::typing::StringLiteral<N>)-> pybind11::typing::StringLiteral<N>’
        103 | struct StringLiteral {
            |        ^~~~~~~~~~~~~
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:103:8: note:   template argument deduction/substitution failed:
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:227:49: note:   mismatched types ‘pybind11::typing::StringLiteral<N>’ and ‘StringLiteral<...auto...>’
        227 | struct handle_type_name<typing::Literal<Literals...>> {
            |                                                 ^~~
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:227:52: error: template argument 1 is invalid
        227 | struct handle_type_name<typing::Literal<Literals...>> {
            |                                                    ^~
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:233:41: error: class template argument deduction failed:
        233 | struct handle_type_name<typing::TypeVar<StrLit>> {
            |                                         ^~~~~~
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:233:41: error: no matching function for call to ‘StringLiteral(StringLiteral<...auto...>)’
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:104:15: note: candidate: ‘template<long unsigned int N> StringLiteral(const char (&)[N])-> pybind11::typing::StringLiteral<N>’
        104 |     constexpr StringLiteral(const char (&str)[N]) { std::copy_n(str, N, name); }
            |               ^~~~~~~~~~~~~
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:104:15: note:   template argument deduction/substitution failed:
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:233:41: note:   mismatched types ‘const char [N]’ and ‘StringLiteral<...auto...>’
        233 | struct handle_type_name<typing::TypeVar<StrLit>> {
            |                                         ^~~~~~
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:103:8: note: candidate: ‘template<long unsigned int N> StringLiteral(pybind11::typing::StringLiteral<N>)-> pybind11::typing::StringLiteral<N>’
        103 | struct StringLiteral {
            |        ^~~~~~~~~~~~~
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:103:8: note:   template argument deduction/substitution failed:
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:233:41: note:   mismatched types ‘pybind11::typing::StringLiteral<N>’ and ‘StringLiteral<...auto...>’
        233 | struct handle_type_name<typing::TypeVar<StrLit>> {
            |                                         ^~~~~~
      /tmp/pip-build-env-36visyz0/overlay/include/pybind11/typing.h:233:47: error: template argument 1 is invalid
        233 | struct handle_type_name<typing::TypeVar<StrLit>> {
            |                                               ^~
      make[2]: *** [CMakeFiles/zxingcpp.dir/build.make:76: CMakeFiles/zxingcpp.dir/zxing.cpp.o] Error 1
      make[1]: *** [CMakeFiles/Makefile2:99: CMakeFiles/zxingcpp.dir/all] Error 2
      make: *** [Makefile:136: all] Error 2
      Traceback (most recent call last):
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 49, in <module>
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 974, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 93, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-36visyz0/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "<string>", line 42, in build_extension
        File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '-j', '8']' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for zxing-cpp
Failed to build zxing-cpp
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (zxing-cpp)
```

The installation of version `2.0.0` works just fine in the same device: 
```
root@jetson-nx:~# pip3 install zxing-cpp==2.0.0
Collecting zxing-cpp==2.0.0
  Downloading zxing-cpp-2.0.0.tar.gz (8.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from zxing-cpp==2.0.0) (1.17.4)
Building wheels for collected packages: zxing-cpp
  Building wheel for zxing-cpp (pyproject.toml) ... done
  Created wheel for zxing-cpp: filename=zxing_cpp-2.0.0-cp38-cp38-linux_aarch64.whl size=788440 sha256=576619151184e12d70095e62390c1abe0e1017e7a5d611f8d500093c67b7df58
  Stored in directory: /root/.cache/pip/wheels/aa/38/5e/031214352ee887115589f89f694ac986448bbe65a73e9b9c53
Successfully built zxing-cpp
WARNING: Error parsing dependencies of distro-info: Invalid version: '0.23ubuntu1'
WARNING: Error parsing dependencies of python-debian: Invalid version: '0.1.36ubuntu1'
Installing collected packages: zxing-cpp
Successfully installed zxing-cpp-2.0.0
```

**Comment by axxel** [comment]
Looks like this is a pybind11 + old gcc issue (see [here](https://github.com/pybind/pybind11/issues/5201#issuecomment-2194069081). The quickest way to get this work might be to upgrade your gcc to at least 10.3.

**Comment by maxvaneck** [comment]
greetings , i seem to be running in the same issue on the community ubuntu 20.04 image when installing the inference package using pip3 
gcc 9.4.0
cmake  = 3.16.3 
python3.8.10
pip3= 24.1.2

as mentioned 2.0.0 installs just fine
